using System;
using System.Collections.Generic;

/// <summary>
/// Data models matching the QR code JSON payload
/// generated by the SAFER AR Floor Plan Editor.
/// </summary>

[Serializable]
public class QRWaypoint
{
    public int id;
    public float distanceM;
    public float bearingRel;  // relative to forward direction (-180 to 180)
    public float bearingAbs;  // absolute bearing from north
}

[Serializable]
public class QRDestination
{
    public float distanceM;
    public float bearingRel;
    public float bearingAbs;
}

[Serializable]
public class EvacuationPlan
{
    public int v;                        // version
    public float scale;                  // meters per pixel
    public float forwardDeg;             // forward direction in absolute degrees
    public List<QRWaypoint> waypoints;   // ordered waypoints
    public QRDestination destination;    // final destination

    /// <summary>
    /// Parse from JSON string (e.g. decoded from QR code).
    /// </summary>
    public static EvacuationPlan FromJson(string json)
    {
        return UnityEngine.JsonUtility.FromJson<EvacuationPlan>(json);
    }
}
